### ISSUE TITLE
cargo install cargo-audit fails due to fail to compile gix-ref v0.41.0

### ISSUE THREAD

**Issue by nathannli** [rustsec/rustsec#1130]
hi beginner at rust here, so not sure if it's an actual issue or just a persona config issue.

When doing `cargo install cargo-audit`, one of the packages that it installs with it is `gix-ref` specifically atm version `0.41.0`. The following compile error occurs:

```
Compiling gix-lock v13.1.0
   Compiling gix-ref v0.41.0
error[E0599]: the method `context` exists for fn item `fn(&mut &[u8]) -> Result<SignatureRef<'_>, ErrMode<_>> {decode::<'_, _>}`, but its trait bounds were not satisfied       
   --> C:\Users\nathan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\gix-ref-0.41.0\src\store\file\log\line.rs:142:46
    |
142 |                 gix_actor::signature::decode.context(StrContext::Expected("<name> <<email>> <timestamp>".into())),
    |                                              ^^^^^^^ method cannot be called due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>} as FnOnce<(&mut _,)>>::Output = Result<_, ErrMode<_>>`
            which is required by `for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>}: winnow::Parser<_, _, _>`
            `<&for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>} as FnOnce<(&mut _,)>>::Output = Result<_, ErrMode<_>>`
            which is required by `&for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>}: winnow::Parser<_, _, _>`
            `<&mut for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>} as FnOnce<(&mut _,)>>::Output = Result<_, ErrMode<_>>`
            which is required by `&mut for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>}: winnow::Parser<_, _, _>`
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
76  +     use winnow::parser::Parser;
    |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `gix-ref` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

I was able to double check this by adding:
```
[dependencies]
gix-ref = "=0.41.0"
```
into my own test project's .toml file and got the same compile error.

However by changing the version to 
```
[dependencies]
gix-ref = "=0.42.0"
```
I did not get that compile error anymore.

**Comment by Shnatsel** [comment]
Thanks for the report! 

For now you can work around this by using `cargo install --locked`

**Comment by Shnatsel** [comment]
There was an accidental semver break somewhere in `gix` is breaking our build. Works with our `Cargo.lock`, but fails on the latest dependencies, which is the default for `cargo install`. @Byron could you take a look?

**Comment by Byron** [comment]
This should be fixed now. I investigated the update issue of `gix-ref` and why it wouldn't pull in the latest version of  it (i.e. 0.41.1, and it turned out that it was all based on other patch-releases needing `gix-actor` in the latest version, so the resolver did the right thing and found a lower version of `gix-ref` which was compatible with the latest version of `gix-actor`, at least on paper (because v0.41.1 restricted `gix-actor` to the latest working version).

Since I wasn't really able to produce a `gix-ref` which can work with both versions of `gix-actor` as it would then have to mix `winnow` 0.5 and 0.6 which doesn't work, I decided to yank `gix` v0.59 entirely as it's the least used.

The culprit here is that an upgrade to `winnow` 0.6 happened without me realizing that this is a breaking change as it's not perfectly isolated. `gix-actor` for instance leaks an error type (for good reason), but that's also causing the issue.

In future, and it's something I usually do, I have to treat breaking `winnow` upgrades as breaking for the API, and even though it's something I kind-of know, this time it slipped by in the reviews. As the upgrade was contributed, it was less obvious to me I suppose, but I have to be more vigilant.

My greatest apologies for the disruption this has caused :/.

**Comment by mcandre** [comment]
Note that unlike package managers for other programming languages, cargo defaults dependency version strings to a loosey goosey automatic upgrade logic. You can enforce a stricter constraint on dependencies by prefixing the version with caret (`^`).

**Comment by tarcieri** [comment]
`^` is the default, which is a SemVer-based match
