### ISSUE TITLE
Minimum supported rust version now 1.51 due to zeroize dependency

### ISSUE THREAD

**Issue by dfreese** [rustsec/rustsec#424]
The README lists the MSRV as 1.46.0, but it looks like the MSRV needs to be bumped to 1.51 due to the zeroize dependency.

We use cargo-audit in a Dockerfile to run it as a github action.  The Dockerfile is as follows

```dockerfile
# Fails with the error below
# FROM rust:1.50.0-buster
# Compiles without error
FROM rust:1.51.0-buster

RUN cargo install --version 0.15.0 cargo-audit
COPY audit.sh /audit.sh

ENTRYPOINT ["/audit.sh"]
```

When using 1.50 and below, we fail with the following error:
> error: failed to compile `cargo-audit v0.15.0`, intermediate artifacts can be found at `/tmp/cargo-installtgnwhE`
> 
> Caused by:
>   failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`
> 
> Caused by:
>   feature `resolver` is required
> 
>   this Cargo does not support nightly features, but if you
>   switch to nightly channel you can add
>   `cargo-features = ["resolver"]` to enable this feature

**Comment by dotdash** [comment]
In the current Cargo.toml, `zeroize` is restricted to versions < 1.4, which should keep MSRV at 1.47. Since `cargo install` ignores the `Cargo.lock` file by default, and 0.15.0 doesn't have that restriction yet, the build picks up the newer, incompatible version of zeroize.

You could try using `cargo install --locked --version 0.15.0 cargo-audit` instead, which makes `cargo install` respect the lockfile and uses the older dependencies from when the crate was released.

**Comment by tarcieri** [comment]
cargo-audit v0.15.1 was released in #430 and should support an MSRV of 1.46

**Comment by dfreese** [comment]
Awesome, thanks!  Crates tend to do well with semver, except for MSRV.  That's the main thing I've seen make long-term stability difficult.

**Comment by tarcieri** [comment]
`zeroize` explicitly calls out MSRV as out-of-scope for SemVer. However, after a `zeroize` 1.5 release that bumps MSRV to 1.56 (for a 2021 edition upgrade) I will likely add MSRV to the crate's SemVer guarantees, and freeze the MSRV there, not bumping it until a hypothetical 2.x release.
