### ISSUE TITLE
cargo audit always fails with "invalid version 0 on git_proxy_options"

### ISSUE THREAD

**Issue by ArekPiekarz** [rustsec/rustsec#431]
`cargo audit`  from version 0.15.1 always fails on any project with the following error:
```
 $ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: invalid version 0 on git_proxy_options; class=Invalid (3)
```
Tested on Manjaro, git 2.33.0, Rust 1.55.0.

**Comment by tarcieri** [comment]
Is this something in your local git configuration? Do you have any proxy options set?

**Comment by demurgos** [comment]
I get the same error on Arch Linux.

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: invalid version 0 on git_proxy_options; class=Invalid (3)
```

I never touched to my Git config beyond setting the email/username.

I initially found this issue with `cargo-edit` (https://github.com/killercup/cargo-edit/issues/487), but I could reproduce it with `cargo-audit` too.

**Comment by tarcieri** [comment]
Weird. We’ve never had anyone report this particular error before.

**Comment by demurgos** [comment]
This may be a bug introduced in a recent version of one of the libs, probably `libgit2`, I only installed `cargo-audit` and `cargo-edit` today.

Some more information:
- I don't notice any issue when using the `git` command line, only through `cargo-edit/audit`
- I don't have any proxy
- I don't have any proxy-related env variable: `http_proxy`, `https_proxy`, `GIT_PROXY_AUTO` , ...
- I don't have any proxy-related config in my `~/.gitconfig`

I found other references to this error message on the internet. In particular it seems that this issue impacted Julia in 2020 but there was not much activity since.
- https://github.com/JuliaLang/julia/issues/33111#issuecomment-612439684
- https://github.com/libgit2/libgit2/issues/5220
- https://github.com/libgit2/libgit2sharp/issues/1769

**Comment by ArekPiekarz** [comment]
@tarcieri I checked variables and places mentioned by @demurgos and there is no proxy configured in them in my setup.

**Comment by ordian** [comment]
See https://github.com/killercup/cargo-edit/pull/488 as a workaround.

**Comment by vrmiguel** [comment]
Happens to me as well :/

```
Linux 5.13.11 (x86-64)
rustc 1.54.0
cargo-audit 0.15.1
git 2.32.0 (no particular special configuration)
```

**Comment by tarcieri** [comment]
Opened #432 with something similar to https://github.com/killercup/cargo-edit/pull/488

**Comment by tarcieri** [comment]
`cargo-audit` v0.15.2 is out with a new `vendored-libgit2` feature. Please give that a try and see if it solves the problem:

```
$ cargo install cargo-audit --features vendored-libgit2
```

**Comment by demurgos** [comment]
I confirm that installing `cargo-audit` with the command provided above worked on my system. Thank you!

**Comment by tarcieri** [comment]
Cool, glad that fixed it

**Comment by tux3** [comment]
Thank you for the fix! Just a note that this issue also affects Debian sid/experimental.  
If I understand correctly, we need to wait for the distributions to update their libgit2 packages?
