### ISSUE TITLE
Fetching rustsec DB does not handle repo contention

### ISSUE THREAD

**Issue by epage** [rustsec/rustsec#490]
Similar to the crate registry (see #489), it looks like fetching the rustsec DB is vulnerable to failing on the same race condition.  We should support retries, whether inside rustsec or by providing enough context to the user so they know they should attempt a retry (looks like all we can tell is there is a "repo" error).

**Comment by Shnatsel** [comment]
Reopening since the approach from #925 runs into issues with stale lockfiles being left if the process is interrupted, causing all subsequent invocations to fail. It's possible to paper over this with signal handlers to some extent but currently the `gix` signal handlers are [not sophisticated enough](https://github.com/rustsec/rustsec/pull/934#discussion_r1288376326).

**Comment by Shnatsel** [comment]
Upon further investigation we found the approach in #925 to be sufficient. I've opened https://github.com/rustsec/rustsec/pull/934 to make it more clear what's happening in case a stale lockfile is present, but the issue described here is fixed.
