### ISSUE TITLE
platforms: TARGET_ARCH and TARGET_OS was removed in 3.0.0

### ISSUE THREAD

**Issue by PureWhiteWu** [rustsec/rustsec#564]
Hello, I found these `TARGET_*`s really useful, would you consider to add them back again?

**Comment by Shnatsel** [comment]
They are superseded by the stdlib `env::consts` module:

https://doc.rust-lang.org/stable/std/env/consts/constant.ARCH.html
https://doc.rust-lang.org/stable/std/env/consts/constant.OS.html

I don't really have a preference on integrating `current-platform`. That will make `platforms` much harder to integrate into non-Cargo build systems, but we can put it behind a feature flag I guess? Or we can just recommend it in the README and docs.rs instead of depending on it.
