### ISSUE TITLE
Linter: Clean up crates.io package name check error

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#622]
Noticed another error as part of fixing #619 via #620

e.g. when a crate name is missing from crates.io we get:
`error: error linting advisory DB ../../: crates.io index error: crates.io package name does not match package name in advisory for rustdecimal`

What is particular about this error is that it does not show which crate causes that and instead hals at middle

It should error same as the others e.g. if advisory toml has invalid keys etc. where it shows which exact advisory caused the error

**Comment by thewizzy** [comment]
Changing the information it provides isn't too difficult. Would the following be sufficient?
`error: error linting advisory DB .cargo\advisory-db: crates.io index error: crates.io package name does not match package name in advisory for rustdecimal. This is part of the malicious crate `rustdecimal` advisory "RUSTSEC-2022-0042".`

The function signature would need to change to pass in the advisory_path in order to show the file at fault.

As an aside, the program counts invalid advisories `self.invalid_advisories += 1;` but pretty much all issues use `fail!` and cause a halt. Do we want to modify it so that it continues linting and collects the issues/issue count until the end. (Something like https://github.com/rustsec/rustsec/compare/main...thewizzy:rustsec:issue-622)

**Comment by Shnatsel** [comment]
I think error: `error linting advisory DB .cargo\advisory-db: crates.io index error: crates.io package name does not match package name in advisory for rustdecimal in RUSTSEC-2022-0042` is cleaner. Or really any less verbose way to indicate the advisory number.

> The function signature would need to change to pass in the advisory_path in order to show the file at fault.

IIRC this is not a problem because this code is private to the linter and does not appear in the public API of the `rustsec` crate so we can make any modifications we want.

There may even be a way to always report the advisory by modifying the type of the error it returns, so that its formatting always includes the advisory number. Carrying a `String` in such an error type seems fine.

> Do we want to modify it so that it continues linting and collects the issues/issue count until the end.

Sounds good to me but is perhaps better done in a separate PR. I'm not 100% sure it won't cause any issues.

**Comment by thewizzy** [comment]
Thank you for your help @Shnatsel 

I will work on a separate PR to stop it halting on failures and report them better at the end.
