### ISSUE TITLE
Pre-built distribution / releases

### ISSUE THREAD

**Issue by passcod** [rustsec/rustsec#66]
It would be nice to have pre-built binaries of the tool available here. This is mostly for CI usage as building the tool in CI inflates build times. This is less an issue with caching, but is still a concern.

**Comment by tarcieri** [comment]
One option for this I had suggested on a [rust-internals thread about upstreaming RustSec](https://internals.rust-lang.org/t/pre-rfc-reviving-security-advisories-in-crates-io-rfc-pr-1752/9017/7) was to distribute `cargo audit` as a rustup component.

**Comment by tarcieri** [comment]
I consider binary releases to be a large responsibility and something that should be done right or not done at all, especially given the security-critical nature of this tool (that said, I do spend a lot of time doing build / release automation for private/enterprise Rust projects).

Here is a quick list of questions about what that might look like:

1. How will binary releases be built? If there's a community build serve / release automation (e.g. @bors) available, I'd be ok with using something like that, but AFAIK there is not (short of releasing as a rustup component). I am **not** ok with "here's a script to build it on your personal computer", and would be strongly in favor of using build automation for releases. Travis CI is a possibility, although my personal preference for something like this is GCP Cloud Build.
2. Which operating systems should receive binary releases? My experience is almost entirely Linux-centric, so unless someone is volunteering to do the work for other operating systems that sounds like the logical starting place.
3. For Linux...
    a. What artifacts will be delivered? Are we producing a static binary linked to musl, or distro-specific packages?
    b. How will release artifacts be delivered? Are we making a tarball of aforementioned static library, or distro-specific packages which can be apt/yum/dnf-installed? All of the above?
    c. How will releases be authenticated? Are we GPG signing that tarball, or using distro-specific GPG integrations to sign distro-specific packages?

If there are satisfactory answers to enough of these questions, and people doing the work, I can consider independent binary releases...

...but personally I *really* don't want to do any of this work, because I'd rather invest the time trying to upstream this tool, which would solve the same problem by making it available as a rustup component.

**Comment by tarcieri** [comment]
tl;dr: of the above: this is something I'm too paranoid to delegate, with too much maintenance burden for me to operate pretty much regardless of the solution, and too much margin for error in a security-critical tool for what feels like a convenience win.

I think the path forward here is upstreaming the project and producing a rustup component using the existing rustup build pipeline.

**Comment by tarcieri** [comment]
I'll throw one option out here which might make sense given my personal circumstances (but may not be what people are generally after here):

I've been meaning to retool part of my company's internal build pipeline to build our in-house OSS projects for public consumption (in a way that we too would consume internally). This pipeline is built on top of Google Cloud Platform and its Cloud Build service, using Cloud Identity + Security Key Enforcement for access control.

I would consider building binary releases of `cargo-audit` on this when it is ready. It's already set up to produce RPMs for CentOS and sign them using one of our GPGs, but could be extended to do things like GitHub releases of statically linked binaries for `musl` targets.

**Comment by Jake-Shadle** [comment]
I think just having `musl` targets in Github releases would be fine, as cargo-audit is just using the lockfile to determine vulnerable crates, it isn't dependent on platform, so I don't see why there would be a need to also have Mac and Windows binaries as well as any use cases for non-musl platforms could still be met by the `cargo install` fallback.

**Comment by epage** [comment]
Someone has brought up the idea of running `cargo-audit` in people's CIs.  `cargo install cargo-audit` is pretty much a non-starter due to how much it'd impact CI times.

So to answer some of the questions raised in the thread for this use case:
- Which platforms? Major CI ones (priority order: Linux, Windows, Mac)
- Distribution method? Github Release in a way compatible with [trust](https://github.com/japaric/trust/) / [gh-install](https://github.com/crate-ci/gh-install)
- How? Take your pick of CIs but it was [relatively easy with Azure Pipelines](https://github.com/crate-ci/committed/blob/master/azure-pipelines.yml#L42)
- How much of a burden? It took me an afternoon to implement and I haven't had to do anything since
- Are there security gaps in this process?  Yes?  Can they be filled?  Some. I still feel that providing pre-built binaries, maybe with a disclaimer, would provide more value to the community than any security risk they introduce.

**Comment by tarcieri** [comment]
> `cargo install cargo-audit` is pretty much a non-starter due to how much it'd impact CI times.

I run `cargo-audit` in CI on the majority of my projects, with minimal impact to CI times, either with:

- Caching (i.e. `cache: cargo` on Travis CI). This does impact CI on the first run, or if the cache is stale, but subsequently runs quickly
- Baking it into a Docker image (on e.g. CircleCI)

**Comment by matklad** [comment]
Let me share rust-analyzer's experience with binary releases:

We use this GitHub actions workflow to build rust-analyzer binaries: https://github.com/rust-analyzer/rust-analyzer/blob/d29c4a2df5ebd039383028738f9bdb4d7b69777e/.github/workflows/release.yaml

It seems nice because it delegates all security concerns to an existing infra:

* builds are run on GitHub actions machines
* artifacts are stored on GitHub's machines
* authentication for publishing release happens via GitHub as well

Ie, it seems reasonably secure, because you don't do have to do anything security-sensitive manually. 

However, I am very much not an expert in secure software distribution, so if I miss something critical, please do tell me.

**Comment by gilescope** [comment]
I'd settle for a pure rust build by default. (zlib fun)

**Comment by tarcieri** [comment]
@matklad thanks! I'd be open to doing releases via GitHub actions.

Some other precedent:

- [rage](https://github.com/str4d/rage/blob/master/.github/workflows/release.yml)
- [rebuilderd](https://github.com/kpcyrd/rebuilderd/blob/master/.github/workflows/binaries.yml)

**Comment by dbrgn** [comment]
@tarcieri I would suggest creating a Docker image as a starting point. The image would essentially contain the following:

```dockerfile
FROM rust:latest
RUN apt-get update && apt-get install -y --no-install-recommends cmake && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-audit
```

So: Latest stable Rust + the latest published cargo-audit release from crates.io, nothing else.

A Dockerfile must be regularly rebuilt and pushed, in order to profit from security updates in the base image. In other projects I maintain, I do that using CircleCI, since they allow cron-style build triggering.

GitHub CI offers recurring builds as well, but requires manually confirming those every 3 months, which is quite annoying.

@tarcieri if you'd agree with this path, I'd be happy to contribute a CircleCI configuration that builds the image and pushes it to Docker Hub, with automatic weekly rebuilds. Something that you'd have to do, would be creating a robo DockerHub account, authorizing CircleCI and adding the push credentials to the project using secret variables.

(Of course I'm open to other suggestions as well. But CircleCI has worked quite well for me in the past.)

**Comment by tarcieri** [comment]
I'd still personally prefer a GitHub Actions-based release process. It's public, logged, and easily attributable.

**Comment by dbrgn** [comment]
Ah, actually, as long as the repo is active, the manual "keepalive" button click will not be required.

I'll send a PR for GitHub CI!

**Comment by tarcieri** [comment]
Awesome, thank you!

**Comment by tarcieri** [comment]
@dbrgn I'm a bit confused what the goal of #332 is.

I feel like the resolution of this particular PR has a pretty specific deliverable, which is building binary releases for major notable operating systems / distributions.

This GitHub Actions workflow does that, as an example:

https://github.com/str4d/rage/blob/main/.github/workflows/release.yml

**Comment by dbrgn** [comment]
Yeah, my goal was not building full binary releases, but instead providing an official Docker image for CI purposes.

I add cargo-audit to all my Rust projects' CI, and even with caching the occasional rebuilds easily take 5-10 minutes. An official image would be really useful to me, and I'm sure to others as well. (I can create and publish such an image myself, of course, but contributing an official setup seemed better.) The crates.io release of cargo-audit has almost 1000 downloads a day, and I'm sure most of those are CI systems based on Docker.

I posted in this thread because an image _is_ a type of binary distribution, and because Docker was mentioned already. However, you are right that #332 does not resolve this issue, it only solves a certain subset of the use cases that would want pre-built binaries 🙂

**Comment by tarcieri** [comment]
I feel your pain with build times, but I feel like the best solution there is pre-built binaries which are created every time a release is tagged

**Comment by mathstuf** [comment]
Why not use the same setup that `rustup` uses for its toolchains?

FWIW, other tools provide pre-built binaries just fine even though they dynamically link to libssl. See [`cargo-tarpaulin`](https://github.com/xd009642/tarpaulin) for an example. I think saying "using `cargo-audit` requires a Debian/Ubuntu/Fedora-based container" is suitable since this is generally a developer tool rather than something one could reasonably argue "must be run on Alpine" or something. But having macOS and Windows binaries would also be useful.

In addition, my issue with providing just Docker containers is that things don't stack well. If I want to make a developer container with `cargo-audit` and `cargo-frobnitz` and both only provide containers, stacking them is…not fun. But then `cargo install` is probably sufficient there too, so who knows.

**Comment by passcod** [comment]
Though I agree in general about the issues with only providing docker images, using

    COPY --from=foo/cargo-audit /usr/bin/cargo-audit /usr/bin/

tends to work pretty well.

@tarcieri sorry to bring up old posts (I'd mostly given up on this issue tbh) but has your stance changed on the security of CI systems as used for releases as per your long post near the top or is there a fundamental difference between github actions and travis in this regard? Or do you wish to have the same criteria you outlined there applied to any proposals regardless? for clarification

**Comment by tarcieri** [comment]
I'd prefer not to integrate with 3rd party systems for this task unless there is a very good reason to do so.

Travis CI in particular has been quite problematic lately due to their [pricing plan changes and drop in the QoS of their OSS tier](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

**Comment by tarcieri** [comment]
As of v0.16.0, we are now building binaries of releases via GitHub Actions using automation added in #337:

https://github.com/rustsec/rustsec/releases/tag/cargo-audit/v0.16.0

Build log here:

https://github.com/rustsec/rustsec/releases/tag/cargo-audit/v0.16.0
