### ISSUE TITLE
Lint `os` field or deprecate in favor of `target` ?

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#671]
Following up from: https://github.com/rustsec/advisory-db/issues/1053

We may want to use platform crate to lint these

But maybe we should deprecate this field in favor of considering well known target triplets

And use e.g. field `target` that conform to platform and Rustc official targets
https://doc.rust-lang.org/nightly/rustc/platform-support.html

Also we probably may want to introduce "exclusion pattern"

**Comment by tarcieri** [comment]
`targets` are much finer grained than `os`.

Both targets and operating systems are automatically extracted from rustc. `os` in particular maps to this enum in the `platforms` crate:

https://docs.rs/platforms/latest/platforms/enum.OS.html

Looking at https://github.com/rustsec/advisory-db/issues/1053 they all appear valid to me?

**Comment by pinkforest** [comment]
Yeah it was fixed

See also: https://github.com/rustsec/rustsec/issues/672

I would like to apply regex to it and exclusion so you can just write !"*windows*" to exclude everything else than windows

Thus it would make sense to go with target as there is opportunity to change it's behaviour e.g. regex / eclusion pattern.

**Comment by tarcieri** [comment]
What's the actual use case for getting as fine-grained as a target triple?

I'm surprised it didn't break while parsing an unknown OS. There shouldn't be need for a "linter" because the strings are directly mapped to enum variants and there's currently no catch-all:

https://docs.rs/rustsec/latest/rustsec/advisory/affected/struct.Affected.html

If anything, I would expect it's too restrictive today.

**Comment by pinkforest** [comment]
See #672 

It's not about being fine-grained but using pattern matching with it and exclusion pattern.

**Comment by tarcieri** [comment]
The `arch` and `os` fields of `affected` map directly to the first two segments of the target triple, but mapping to enum variants defined in the `platforms` crate, rather than a string-based representation.

I don't think it makes sense to migrate to using raw target triple strings. Instead we collect structured information.

**Comment by pinkforest** [comment]
So granted we are not doing target

What if we use the platform crate to validate the os variants ?

**Comment by pinkforest** [comment]
The linter seems to not do anything with the os / arch ?

https://github.com/rustsec/rustsec/blob/main/rustsec/src/advisory/linter.rs#L254

**Comment by tarcieri** [comment]
As I mentioned earlier, there's no need to "lint" because the TOML strings are parsed to enum variants:

https://docs.rs/rustsec/latest/rustsec/advisory/affected/struct.Affected.html#structfield.os

What's an example of an invalid one which was allegedly working?

**Comment by pinkforest** [comment]
Ah so it was screened via enum variant, I failed to internalise this.

`RustSec error: parse error: error parsing ../../crates/invalid-os/RUSTSEC-0000-0000.md: parse error: Unrecognized value 'bar' for target_os for key `affected.os` at line 12 column 1`

This is what manually updated them back in the time - 18 April:
https://github.com/rustsec/advisory-db/pull/1222/files

so we actually use the platforms to validate it but obviously platforms crate was changed

My error to understand this so I'll close since it is working today as intended.
