### ISSUE TITLE
Versions::is_vulnerable vs informational

### ISSUE THREAD

**Issue by kornelski** [rustsec/rustsec#698]
I suspect `Versions.is_vulnerable` should be called something more neutral, like `is_affected` or `is_applicable`, because it can be on `Advisory` that is about maintenance, and that's not a vulnerability.

**Comment by pinkforest** [comment]
Maintenance status is a vulnerability as others and we are not complicating that further.

This vulnerability presents increased malicious takeover chance and / or other supply chain related security vulnerabilities.

**Vulnerability** - _the quality or state of being exposed to the possibility of being attacked or harmed_

Rust ecosystem favors large amounts of small dependencies and often these are from solo maintainers who aren't necessarily established or care too much about to maintain some little piece of software.

Where as the legacy security databases were spun up during the dark ages of "Write it all yourself" and didn't have much package management to go with to supplement / enrich their software with that served as a tiny cog in a big wheel.

Whether the vulnerability is acceptable to someone as such is another opinion but not opinion to dictate to the whole userbase based on one risk profile isn't what we are doing.

Nonetheless otherwise I agree that `is_vulnerable` is perhaps just subotimal API from style wise and nothing more changing public APIs for stylistic resons isn't what we are probably going to be doing.
