### ISSUE TITLE
cargo audit panics with Error("invalid leading zero in pre-release identifier") on volatile crate

### ISSUE THREAD

**Issue by andersk** [rustsec/rustsec#759]
```console
$ cargo init
     Created binary (application) package
$ cargo add volatile
    Updating crates.io index
      Adding volatile v0.4.5 to dependencies.
             Features:
             - unstable
    Updating crates.io index
$ cargo audit 
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 469 security advisories (from /home/anders/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (2 crate dependencies)
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Error("invalid leading zero in pre-release identifier")
Location: /build/cargo-audit-0.17.4-vendor.tar.gz/rustsec/src/cached_index.rs:58

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

A backtrace shows that the crash happens at this `unwrap()`:

https://github.com/rustsec/rustsec/blob/0b05e18c0f719076d56942e6b0e1e13dec11a428/rustsec/src/cached_index.rs#L54-L59

because one of the old [versions](https://crates.io/crates/volatile/versions) of the `volatile` crate is `0.4.0-alpha.00`, which fails to parse as `semver::Version`.

**Comment by Shnatsel** [comment]
Okay, so that version is not actually compliant with the [semver specification](https://semver.org/#spec-item-9):

> Numeric identifiers MUST NOT include leading zeroes

I believe `semver` crate is correct in rejecting this version, but crates.io allowed it anyway and now there's no way to remove it from the database.

There's the [`lenient_semver`](https://docs.rs/lenient_semver) crate, but it seems to be way too lenient.

The least terrible solution I see is to ignore malformed versions and print a warning about that when loading the crates index. Worst-case scenario is that if a malformed semver is being depended on and is yanked, the yanked status will not be reported. @tarcieri thoughts?

**Comment by Shnatsel** [comment]
The `cargo-lock` crate and other parts of `rustsec` crate will also fail here, but only if the dependency is actually in the `Cargo.lock` file; so errors are triggered here but not in other parts of `cargo audit` only when the crate with the malformed version is not being depended, so we don't want to know about its status regardless.

I'm now convinced that simply ignoring the malformed version in this code is the right solution.

**Comment by Shnatsel** [comment]
Or we could just not attempt to parse crates.io registry versions as SemVer. That works too.

**Comment by Shnatsel** [comment]
I confirmed https://github.com/rustsec/rustsec/pull/762 fixes using the `volatile` crate as a dependency.

**Comment by Shnatsel** [comment]
Run `cargo install --force cargo-audit` to get the version with the fix. `--force` is needed because the fix was in `rustsec` crate, not in `cargo-audit` itself.
