### ISSUE TITLE
Use a git dependency to circumvent cargo-audit's reporting

### ISSUE THREAD

**Issue by qtfkwk** [rustsec/rustsec#792]
May be related to <https://github.com/rustsec/rustsec/issues/696>?

Noticed this while tracking down https://rustsec.org/advisories/RUSTSEC-2022-0044 / https://github.com/rustsec/advisory-db/pull/1191#issuecomment-1398854358 ...

Repro:

```
cargo new test-cargo-audit
cd test-cargo-audit
cargo add markdown@1.0.0-alpha.5
cargo audit # shows RUSTSEC-2022-0044
cargo remove markdown
cargo add markdown --git https://github.com/wooorm/markdown-rs --tag 1.0.0-alpha.5
cargo audit # all good! (but it's a false positive)
```

Would think that it should link by the repo URL in crates.io and report the same advisory, unless there's a reason... for example, it did detect that the advisory was for the prior repo which changed to the current repo, but skips this if the dep is not a git repo?

**Comment by tarcieri** [comment]
The scope of @RustSec is explicitly defined as:

> The [RustSec Advisory Database](https://github.com/RustSec/advisory-db) is a repository of security advisories filed against Rust crates published via [crates.io](https://crates.io/)

Repositories fetched via git are explicitly out of scope. More concretely, when extracting dependencies from Cargo.lock, we only examine `[package]`s with the following source:

```toml
source = "registry+https://github.com/rust-lang/crates.io-index"
```

While some kind of heuristics to extract data from the crates.io API to compare them against a `[package]` with a `git+https://` source that just so happens to match the `repo` line is hypothetically possible, the `repo` URI is unauthenticated and easily spoofed, that API integration doesn't exist today so it would be adding quite a bit complexity, and the end result would be quite brittle and may potentially generate false positives.

Generally we've eschewed things which are quite complex/brittle and might generate false positives because we're concerned about alert fatigue.

**Comment by qtfkwk** [comment]
Makes sense. Appreciate the detailed response. In future, will consider security implications of git dependencies. Thank you!
